### ISSUE TITLE
where all the forms at bitch?

### ISSUE THREAD

**Issue by fundies** [enigma-dev/wxENIGMA#1]
only object has half a form here

**Comment by RobertBColton** [comment]
That's all there is, I was having a hard time using wx layouts because they suck (DPI support is confusing, layouts are confusing and redundant). Don't even bother looking at the old wxENIGMA either because it has zero and it's also all code. This is as far as I got captain fundies, honest.

**Comment by fundies** [comment]
So should I develop radialgm or are you gonna post new ide in next 5 sec?

**Comment by RobertBColton** [comment]
Yes, we're not building this wx piece of shit, I'll talk to you after bit about the other piece of shit we are going to build. It is RadialGM, but I have to upload the new source, we're not using that old one either. RGM is just the codename remember, its executable will just be ENIGMA.exe.

**Comment by fundies** [comment]
so upload new source so i can work on it
